# Generated by Django 3.2 on 2021-05-26 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pmlprofile', '0002_alter_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meeting_type', models.CharField(choices=[('QM', 'Quartely Meeting'), ('SM', 'Special Meeting'), ('YF', 'Year-end Function'), ('XM', 'Extraordinary Meeting')], max_length=200)),
                ('alt_venue', models.CharField(blank=True, max_length=300, null=True)),
                ('minutes', models.FileField(max_length=300, upload_to='pml_documents/%Y/%M')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pmlprofile.profile')),
            ],
        ),
    ]
