# Generated by Django 3.2 on 2021-06-16 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pmlprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meeting_type', models.CharField(choices=[('Quartely Meeting', 'Quartely Meeting'), ('Special Meeting', 'Special Meeting'), ('Year-end Function', 'Year-end Function'), ('Extraordinary Meeting', 'Extraordinary Meeting')], max_length=200)),
                ('alt_venue', models.CharField(blank=True, max_length=300, null=True)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pmlprofile.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=True)),
                ('absence_reason', models.CharField(blank=True, choices=[('Family Commitment', 'Family Commitment'), ('Ill-Health', 'Ill-Health'), ('Work Commitment', 'Work Commitment'), ('Funeral Attendance', 'Funeral Attendance')], max_length=300, null=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='events.meeting')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='pmlprofile.profile')),
            ],
        ),
    ]
