# Generated by Django 3.2 on 2021-05-26 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pmlprofile', '0002_alter_profile_photo'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='meeting',
            name='minutes',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to='pml_documents/%Y/%M'),
        ),
        migrations.CreateModel(
            name='AttendanceRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=True)),
                ('absence_reason', models.CharField(blank=True, choices=[('FC', 'Family Commitment'), ('IH', 'Ill-Health'), ('WC', 'Work Commitment'), ('FA', 'Funera Attendance')], max_length=300, null=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='events.attendance')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='pmlprofile.profile')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='meeting',
            field=models.ForeignKey(max_length=300, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='events.meeting'),
        ),
    ]
