# Generated by Django 3.2 on 2021-11-05 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pmlprofile', '0009_delete_memberaccount'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('deceased_type', models.CharField(choices=[('Member', 'Member'), ('Beneficiary', 'Beneficiary')], max_length=100)),
                ('deceased_name', models.CharField(max_length=200)),
                ('venue', models.CharField(max_length=200)),
                ('bereaved_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmlprofile.profile')),
            ],
        ),
        migrations.AlterField(
            model_name='attendance',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='pmlprofile.profile'),
        ),
        migrations.CreateModel(
            name='FuneralAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=True)),
                ('absence_reason', models.CharField(blank=True, choices=[('Family Commitment', 'Family Commitment'), ('Ill-Health', 'Ill-Health'), ('Work Commitment', 'Work Commitment'), ('Funeral Attendance', 'Funeral Attendance')], max_length=300, null=True)),
                ('funeral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='events.funeral')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='pmlprofile.profile')),
            ],
        ),
    ]
