# Generated by Django 3.2 on 2021-05-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210526_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceregister',
            name='absence_reason',
            field=models.CharField(blank=True, choices=[('Family Commitment', 'FC'), ('Ill-Health', 'IH'), ('Work Commitment', 'WC'), ('Funeral Attendance', 'FA')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(choices=[('Quartely Meeting', 'QM'), ('Special Meeting', 'SM'), ('Year-end Function', 'YF'), ('Extraordinary Meeting', 'XM')], max_length=200),
        ),
    ]
