# Generated by Django 3.2 on 2021-11-05 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pmlprofile', '0009_delete_memberaccount'),
        ('events', '0002_auto_20211105_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funeral',
            name='deceased_name',
        ),
        migrations.AddField(
            model_name='funeral',
            name='deceased_beneficiary',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pmlprofile.beneficiary'),
        ),
    ]
