# Generated by Django 3.2 on 2021-05-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210526_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceregister',
            name='absence_reason',
            field=models.CharField(blank=True, choices=[('Family Commitment', 'Family Commitment'), ('Ill-Health', 'Ill-Health'), ('Work Commitment', 'Work Commitment'), ('Funeral Attendance', 'Funeral Attendance')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(choices=[('Quartely Meeting', 'Quartely Meeting'), ('Special Meeting', 'Special Meeting'), ('Year-end Function', 'Year-end Function'), ('Extraordinary Meeting', 'Extraordinary Meeting')], max_length=200),
        ),
    ]
