# Generated by Django 3.2 on 2021-05-26 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pmlprofile', '0002_alter_profile_photo'),
        ('events', '0004_auto_20210526_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='absence_reason',
            field=models.CharField(blank=True, choices=[('Family Commitment', 'Family Commitment'), ('Ill-Health', 'Ill-Health'), ('Work Commitment', 'Work Commitment'), ('Funeral Attendance', 'Funeral Attendance')], max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_present',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='pmlprofile.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='events.meeting'),
        ),
        migrations.DeleteModel(
            name='AttendanceRegister',
        ),
    ]
