# Generated by Django 3.2 on 2021-06-09 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20210526_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='minutes',
        ),
    ]
