# Generated by Django 3.2 on 2021-05-05 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middlename', models.CharField(blank='True', max_length=100, null='True')),
                ('birth_date', models.DateField()),
                ('mobile_phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Deceased', 'Deceased'), ('Article 11.3', 'Article 11.3'), ('Terminated', 'Terminated')], default='Active', max_length=20)),
                ('status_date', models.DateField(blank='True', null='True')),
                ('address', models.TextField(max_length=200)),
                ('town_city', models.CharField(max_length=200)),
                ('district_metro', models.CharField(max_length=250)),
                ('province', models.CharField(choices=[('Eastern Cape', 'EC'), ('Free State', 'FS'), ('Gauteng', 'GP'), ('KwaZulu Natal', 'KZN'), ('Limpopo', 'LP'), ('Mpumalanga', 'MP'), ('Northern Cape', 'NC'), ('North West', 'NW'), ('Western Cape', 'WC')], max_length=100)),
                ('photo', models.ImageField(default='/static/img/avatar.png', upload_to='photos/%Y/%m/%d')),
                ('alt_address', models.TextField(blank='True', null='True')),
                ('alt_phone', models.CharField(blank='True', max_length=50, null='True')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee_name', models.CharField(choices=[('Exeutive Committee', 'EXCO'), ('Finance Committee', 'FINCOM'), ('Constitutional Committee', 'CONCOM'), ('Disciplinary Committee', 'DC'), ('Events Committee', 'EC'), ('Compassion Committee', 'COMPCOM')], max_length=200)),
                ('portfolio', models.CharField(choices=[('Chairperson', 'Chairperson'), ('Deputy Chairperson', 'Deputy Chairperson'), ('Secetary-General', 'Secretary-General'), ('Deputy Secretary General', 'Deputy Secretary-General'), ('Treasurer', 'Treasurer'), ('Events Coordinator', 'Events Cordinator'), ('Member of EXCO', 'MEC'), ('Convenor', 'Convenor')], max_length=200)),
                ('start_date', models.DateField(blank='False', null='false')),
                ('end_date', models.DateField()),
                ('member', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('beneficiary_type', models.CharField(choices=[('Spouse', 'Spouse'), ('Child', 'Child'), ('Father', 'Father'), ('Mother', 'Mother'), ('Father-in-Law', 'Father-in-Law'), ('Mother-in-Law', 'Mother-in-Law'), ('Parent Proxy', 'Parent Proxy')], default='Spouse', max_length=100)),
                ('birth_date', models.DateField()),
                ('beneficiary_status', models.CharField(choices=[('Active', 'Active'), ('Article 20.3', 'Article 20.3'), ('Deceased', 'Deceased'), ('Inactive', 'Inactive')], default='Active', max_length=100)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='pmlprofile.profile')),
            ],
        ),
    ]
