# Generated by Django 3.2 on 2021-05-08 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortname', models.CharField(max_length=150)),
                ('middlename', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('mobile_phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Deceased', 'Deceased'), ('Suspended', 'Suspended'), ('Terminated', 'Terminated')], default='Active', max_length=20)),
                ('status_date', models.DateField(blank=True, null=True)),
                ('address', models.TextField(max_length=200)),
                ('town_city', models.CharField(max_length=200)),
                ('district_metro', models.CharField(max_length=250)),
                ('province', models.CharField(choices=[('Eastern Cape', 'Eastern Cape'), ('Free State', 'Free State'), ('Gauteng', 'Gauteng'), ('KwaZulu Natal', 'KwaZulu Natal'), ('Limpopo', 'Limpopo'), ('Mpumalanga', 'Mpumalanga'), ('Northern Cape', 'Northern Cape'), ('North West', 'North West'), ('Western Cape', 'Western Cape')], max_length=100)),
                ('photo', models.ImageField(default='/static/img/default.png', upload_to='member_photos/%Y')),
                ('alt_address', models.TextField(blank=True, null=True)),
                ('alt_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('beneficiary_type', models.CharField(choices=[('Spouse', 'Spouse'), ('Child', 'Child'), ('Father', 'Father'), ('Mother', 'Mother'), ('Father-in-Law', 'Father-in-Law'), ('Mother-in-Law', 'Mother-in-Law'), ('Parent Proxy', 'Parent Proxy')], default='Spouse', max_length=100)),
                ('birth_date', models.DateField()),
                ('beneficiary_status', models.CharField(choices=[('Active', 'Active'), ('Article 20.3', 'Article 20.3'), ('Deceased', 'Deceased'), ('Inactive', 'Inactive')], default='Active', max_length=100)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='pmlprofile.profile')),
            ],
        ),
    ]
