# Generated by Django 3.2 on 2021-05-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmlprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='default2.png', upload_to='member_photos/%Y'),
        ),
    ]
