# Generated by Django 3.2 on 2021-05-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmlprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='proxy',
            field=models.CharField(blank=True, choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Father-in_Law', 'Father-in-Law'), ('Mother-in-Law', 'Mother-in-Law')], max_length=100, null=True),
        ),
    ]
