# Generated by Django 3.2 on 2021-05-11 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmlprofile', '0002_beneficiary_proxy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficiary',
            options={'ordering': ['-id']},
        ),
    ]
