# Generated by Django 3.2 on 2021-05-11 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmlprofile', '0003_alter_beneficiary_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficiary',
            options={'ordering': ('member__id', 'id')},
        ),
    ]
