# Generated by Django 3.2 on 2021-07-27 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmlprofile', '0003_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficiary',
            options={'ordering': ('member__id',)},
        ),
    ]
