# Generated by Django 3.2 on 2021-07-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmlprofile', '0004_alter_beneficiary_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='lapse_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lapse_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
