# Generated by Django 3.2 on 2021-05-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmlprofile', '0004_alter_beneficiary_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Executive Committee', 'Executive Committee'), ('Finance Committee', 'Finance Committee'), ('Constitutional Committee', 'Constitutional Committee'), ('Disciplinary Committee', 'Disciplinary Committee'), ('Events Committee', 'Events Committee'), ('Compassion Committee', 'Compassion Committee')], max_length=200)),
                ('portfolio', models.CharField(choices=[('Chairperson', 'Chairperson'), ('Deputy Chairperson', 'Deputy Chairperson'), ('Secetary-General', 'Secretary-General'), ('Deputy Secretary-General', 'Deputy Secretary-General'), ('Treasurer-General', 'Treasurer-General'), ('Events Coordinator', 'Events Cordinator'), ('Member of EXCO', 'Member of Exco'), ('Convenor', 'Convenor'), ('Ex Officio', 'Ex Officio')], max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('profile', models.ManyToManyField(blank=True, null=True, to='pmlprofile.Profile')),
            ],
        ),
    ]
