# Generated by Django 3.2 on 2021-07-31 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmlprofile', '0005_auto_20210729_1803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficiary',
            options={'ordering': ('member__id',), 'verbose_name_plural': 'Beneficiaries'},
        ),
    ]
