# Generated by Django 3.2 on 2021-05-16 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pmlprofile', '0005_committee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committee',
            name='profile',
        ),
        migrations.AddField(
            model_name='committee',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pmlprofile.profile'),
        ),
    ]
