# Generated by Django 3.2 on 2021-05-16 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmlprofile', '0006_auto_20210516_1957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='committee',
            options={'ordering': ['id']},
        ),
    ]
