# Generated by Django 3.2 on 2021-08-28 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmlprofile', '0006_alter_beneficiary_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age_group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
