# Generated by Django 3.2 on 2021-09-22 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmlprofile', '0008_memberaccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MemberAccount',
        ),
    ]
