# Generated by Django 3.2 on 2021-11-10 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmlprofile', '0009_delete_memberaccount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('user__id',), 'verbose_name_plural': 'Member Profiles'},
        ),
    ]
