# Generated by Django 3.2 on 2021-09-22 13:41

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pmlprofile', '0008_memberaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('balance_brought_forward', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10)),
                ('premiums', models.DecimalField(decimal_places=2, default=Decimal('150.0'), max_digits=10)),
                ('funeral_topup', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10)),
                ('transport_topup', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10)),
                ('fines', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10)),
                ('total_debits', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10)),
                ('cash_deposit', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10)),
                ('adjustments', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10)),
                ('total_receipts', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10)),
                ('net_movement', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10)),
                ('total_outstanding', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='pmlprofile.profile')),
            ],
            options={
                'ordering': ('-date', 'id'),
            },
        ),
    ]
