# Generated by Django 3.2 on 2021-09-22 14:29

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pmlfin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberaccount',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberaccount',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='memberaccount',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
