# Generated by Django 3.2 on 2021-09-22 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmlfin', '0002_auto_20210922_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberaccount',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
