# Generated by Django 3.2 on 2021-10-07 20:32

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pmlfin', '0003_alter_memberaccount_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opening_bank_bal', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10)),
                ('expenses', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10)),
                ('income', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10)),
                ('closing_bank_bal', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('trading_name', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('purchase_date', models.DateField()),
                ('num_shares', models.IntegerField()),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10)),
                ('purchase_value', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('current_share_price', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10)),
                ('current_value', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='pmlfin.company')),
            ],
        ),
        migrations.AlterField(
            model_name='memberaccount',
            name='total_debits',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.0'), max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='memberaccount',
            name='total_receipts',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.0'), max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Wealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closing_cash_balance', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10)),
                ('notice_acc_balance', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10)),
                ('shares_total', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10)),
                ('date', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='shares', to='pmlfin.share')),
            ],
            options={
                'verbose_name_plural': 'Wealth',
            },
        ),
    ]
