# Generated by Django 3.2 on 2021-11-06 21:51

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pmlfin', '0004_auto_20211007_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Co',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('shortname', models.CharField(blank=True, max_length=30, null=True)),
                ('logo', models.ImageField(default='static/img/pml_logo5.png', upload_to='')),
                ('no_shares', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='memberaccount',
            options={'ordering': ['-date', 'id']},
        ),
        migrations.RenameField(
            model_name='wealth',
            old_name='shares_total',
            new_name='monthly_shares_total',
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(default='static/img/pml_logo5.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='wealth',
            name='total_net_wealth',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10),
        ),
        migrations.RemoveField(
            model_name='wealth',
            name='date',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='wealth',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='share',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmlfin.co'),
        ),
    ]
