# Generated by Django 3.2 on 2021-10-11 18:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pmlfin', '0004_auto_20211007_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wealth',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
