# Generated by Django 3.2 on 2021-10-11 20:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmlfin', '0005_alter_wealth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.URLField(blank=True, null=True, verbose_name='Brand Logo'),
        ),
        migrations.AddField(
            model_name='wealth',
            name='total_net_wealth',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10),
        ),
    ]
