# Generated by Django 3.2 on 2021-10-11 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmlfin', '0006_auto_20211011_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(default='static/img/pml_logo5.png', upload_to=''),
        ),
    ]
