# Generated by Django 3.2 on 2021-10-13 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pmlfin', '0007_alter_company_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wealth',
            old_name='shares_total',
            new_name='monthly_shares_total',
        ),
        migrations.AlterField(
            model_name='share',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmlfin.company'),
        ),
    ]
