# Generated by Django 3.2 on 2021-10-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmlfin', '0008_auto_20211013_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Co',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('shortname', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
