# Generated by Django 3.2 on 2021-10-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmlfin', '0009_co'),
    ]

    operations = [
        migrations.AddField(
            model_name='co',
            name='logo',
            field=models.ImageField(default='static/img/pml_logo5.png', upload_to=''),
        ),
    ]
