# Generated by Django 3.2 on 2021-10-14 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pmlfin', '0010_co_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmlfin.co'),
        ),
    ]
