# Generated by Django 3.2 on 2021-10-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmlfin', '0011_alter_share_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='co',
            name='no_shares',
            field=models.IntegerField(default=0),
        ),
    ]
