# Generated by Django 3.2 on 2021-10-18 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmlfin', '0012_co_no_shares'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberaccount',
            options={'ordering': ['-date', 'id']},
        ),
    ]
