# Generated by Django 3.2 on 2021-10-18 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmlfin', '0013_alter_memberaccount_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberaccount',
            options={'ordering': ['date', 'id']},
        ),
    ]
