# Generated by Django 3.2 on 2021-06-09 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0006_remove_meeting_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Minutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('minutes', models.FileField(upload_to='minutes/%Y/%M')),
                ('title', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='events.meeting')),
            ],
        ),
    ]
