# Generated by Django 3.2 on 2021-06-16 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Minutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('doc', models.FileField(upload_to='minutes/%Y/%F')),
                ('title', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='meeting', to='events.meeting')),
            ],
        ),
    ]
