# Generated by Django 3.2 on 2021-06-09 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_meeting_minutes'),
        ('docs', '0003_alter_minutes_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minutes',
            name='title',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='meeting', to='events.meeting'),
        ),
    ]
