# Generated by Django 3.2 on 2021-06-09 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_alter_minutes_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='minutes',
            old_name='minutes',
            new_name='doc',
        ),
    ]
