# Generated by Django 3.2 on 2021-06-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0006_alter_minutes_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minutes',
            name='doc',
            field=models.FileField(upload_to='minutes/%Y/%M'),
        ),
    ]
