# Generated by Django 3.2 on 2021-10-15 15:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=350)),
                ('lat', models.DecimalField(decimal_places=6, default=Decimal('0.0'), max_digits=8)),
                ('lon', models.DecimalField(decimal_places=6, default=Decimal('0.0'), max_digits=8)),
            ],
        ),
    ]
