# Generated by Django 3.2 on 2021-10-25 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pmlprofile', '0009_delete_memberaccount'),
        ('geoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='lon',
            new_name='lng',
        ),
        migrations.RemoveField(
            model_name='location',
            name='address',
        ),
        migrations.AlterField(
            model_name='location',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='pmlprofile.profile'),
        ),
    ]
