# Generated by Django 3.2 on 2021-10-26 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pmlprofile', '0009_delete_memberaccount'),
        ('geoApp', '0002_auto_20211025_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pmlprofile.profile'),
        ),
    ]
